name: Daily render ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Trigger every 10 minutes
  workflow_dispatch:        # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Random sleep before ping
        run: |
          # Pick a random number of seconds between 0 and 600 (10 minutes)
          SECONDS=$((RANDOM % 600))
          echo "Sleeping for $SECONDS seconds..."
          sleep $SECONDS

      - name: Run cURL on Website
        run: curl -I ${{ secrets.RENDER_URL }}
